<CalculatorWidget>:
    orientation: 'vertical'
    Label:
        text: f"Num1: {root.num1}"
    Label:
        text: f"Num2: {root.num2}"
    Label:
        text: f"Soma: {root.sum_result}"
    BoxLayout:
        size_hint_y: None
        height: 40
        Button:
            text: "+"
            on_press: root.num1 += 1
        Button:
            text: "-"
            on_press: root.num2 += 1
